queue_rules:
  - name: default
    # When auto-updating PRs for the base branch, rebase.
    update_method: rebase
    merge_method: merge
pull_request_rules:
  - name: Automatically rebase and merge pull requests
    actions:
      queue:
        name: default
    conditions:
      - label=ready-for-merge
      - label!=WIP
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
  - name: Delete head branch after merge
    actions:
      delete_head_branch: {}
    conditions:
      - merged
