# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: end-of-file-fixer
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    - id: isort
      args: [--profile=black, --project=rnnt_train, --project=internal_rnnt_train]
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    - id: black
      language_version: python3
      args: [--line-length=88]
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.1.5
  hooks:
    # Fix unused imports
    - id: ruff
      args: [--select, F401, --fix]
      # This also excludes the smoke tests in myrtle-training
      exclude: training/tests/test_smoke_tests.py
- repo: https://github.com/tcort/markdown-link-check
  rev: v3.11.2
  hooks:
    - id: markdown-link-check
      args: [
        "-q",
        "--alive=200,404"
      ]
      # Later versions of node are incompatible with Ubuntu 18
      language_version: "17.9.1"
- repo: https://github.com/PyCQA/flake8
  rev: 7.0.0
  hooks:
  - id: flake8
    args: [--max-line-length=92, "--extend-ignore=E203,F401,F722"]
